/* Testing fields generated by CM points in case I */

R<x> := PolynomialRing(Rationals());
num := 46656*x^6 - 233280*x^5 + 408240*x^4 - 280800*x^3 + 56700*x^2 + 5868*x + 125;
den := 10368*x;

j := 1728*(1 - num/den);
numj := Numerator(j); denj := Denominator(j);

print "Check factorization (arbitrary, divides 3, divides 2):";
print Factorization(Denominator(j));
print Factorization(Numerator(j));
print Factorization(Numerator(j - 1728));

K := NumberField(x^2 + 7);
j0 := 16581375;
//K := NumberField(x^2 + 11);
//j0 := -32768;
//K := NumberField(x^2 + 43);
//j0 := -884736000;

S<xK> := PolynomialRing(K);
numjK := S ! numj; denjK := S ! denj;

p := numj - j0*denj;
pK := S ! p;

/*
L<r> := RelativeSplittingField(p);
q := MinimalPolynomial(r);
qK := S ! q;
qK := Factorization(qK)[1][1];
L := NumberField(qK);
print GaloisGroup(L);
*/

Fac := Factorization(pK);
pK := Fac[1][1];
L<r> := NumberField(pK);

print "Galois group:";
print GaloisGroup(L);
print "Abelian?";
print IsAbelian(GaloisGroup(L));

s := r*(r^2 - 11/3*r + 125/36);
q := MinimalPolynomial(s, Rationals());
qK := MinimalPolynomial(s, K);

// -6 is correct
d := -6;
rK := Evaluate(qK, d*xK^2);
Fac := Factorization(rK);
M := NumberField(Fac[1][1]);
print "Normal?";
print IsNormal(M);
print "Galois group:";
print GaloisGroup(M);
print "Abelian?";
print IsAbelian(GaloisGroup(M));
